apiVersion: batch/v1
kind: Job
metadata:
  name: model-toon-pipeline-init-job
spec:
  template:
    spec:
      containers:
        - name: model-toon-pipeline-container
          image: model_toon_pipeline:latest
          imagePullPolicy: IfNotPresent
          command: ["echo", "Init job completed"]
      restartPolicy: Never
  backoffLimit: 0
